/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper

public enum KeyPress:String {
    case none = "NONE" //0
    case enter = "ENTER" //40
    case esc = "ESC" //41
    case backspace = "BACKSPACE" //42
    case tab = "TAB" //43
    case star = "STAR" //85
    case button_1 = "BUTTON_1" //58
    case button_2 = "BUTTON_2" //59
    case button_3 = "BUTTON_3" //60
    case button_4 = "BUTTON_4" //61
    case button_5 = "BUTTON_5" //62
    case button_6 = "BUTTON_6" //63
    case button_7 = "BUTTON_7" //64
    case button_8 = "BUTTON_8" //65
    case digit_1 = "DIGIT_1" //89
    case digit_2 = "DIGIT_2" //90
    case digit_3 = "DIGIT_3" //91
    case digit_4 = "DIGIT_4" //92
    case digit_5 = "DIGIT_5" //93
    case digit_6 = "DIGIT_6" //94
    case digit_7 = "DIGIT_7" //95
    case digit_8 = "DIGIT_8" //96
    case digit_9 = "DIGIT_9" //97
    case digit_0 = "DIGIT_0" //98
}
