platform :ios, '8.0'

use_frameworks!

target 'CloverConnector_Example' do
  
  pod 'CloverConnector', :path => '../'
#  pod 'Starscream', "1.1.4"
#  pod "ObjectMapper", "1.5.0"
#  pod "SwiftyJSON", "2.4.0"

  target 'CloverConnector_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end

