sdk: iphoneos
theme: fullwidth
podspec: CloverConnector.podspec
module: CloverConnector
theme: apple
output: 3.0.0/docs
clean: true
github-url: https://github.com/clover/remote-pay-ios
swift-version: 4.2
copyright: 'Copyright © 2018 Clover Network, Inc. All rights reserved.'
custom_categories:
   - name: API
     children:
     - ICloverConnector
     - CloverConnectorFactory 
     - ICloverConnectorListener
     - DefaultCloverConnectorListsner
     - WebSocketDeviceConfiguration
     - NetworkDeviceConfiguration
   - name: Payment
     children:
     - SaleRequest
     - SaleResponse
     - AuthRequest
     - AuthResponse
     - PreAuthRequest
     - PreAuthResponse
     - ManualRefundRequest
     - ManualRefundResponse
     - TipAdjustAuthRequest
     - TipAdjustAuthResponse
     - CapturePreAuthRequest
     - CapturePreAuthResponse
     - RefundPaymentRequest
     - RefundPaymentResponse
     - VoidPaymentRequest
     - VoidPaymentResponse
     - VoidPaymentRefund
     - VoidPaymentRefundResponse
     - RetreivePendingPaymentRequest
     - RetrievePendingPaymentResponse
     - RetrievePaymentRequest
     - RetrievePaymentResponse
     - CloseoutRequest
     - CloseoutResponse
     - ReadCardDataRequest
     - ReadCardDataResponse
     - VaultCardRequest
     - VaultCardResponse
     - ConfirmPaymentRequest
     - VerifySignatureRequest
     - Signature
   - name: Device
     children:
     - MerchantInfo
     - DeviceInfo
     - DisplayOrder
     - DisplayLineItem
     - DisplayDiscount
     - DisplayPayment
     - PrintPaymentReceiptMessage
     - PrintPaymentMerchantCopyReceiptMessage
     - PrintRefundPaymentReceiptMessage
     - PrintPaymentDeclineReceiptMessage
     - PrintManualRefundReceiptMessage
     - PrintManualRefundDeclineReceiptMessage
     - ShowPaymentReceiptOptions
     - RetrieveDeviceStatusRequest
     - RetrieveDeviceStatusResponse
     - SendDebugLog
   - name: Custom Activities
     children:
     - CustomActivityRequest
     - CustomActivityResponse
     - MessageToActivity
     - MessageFromActivity
   - name: Pairing
     children:
     - PairingDeviceConfiguration
exclude:
- "../**/action/*.swift"
- "../**/operations/*.swift"
# - "../**/AddDiscountAction.swift"
# - "../**/AddLineItemAction.swift"
# - "../**/*Message.swift"
# - "../**/ActivityRequest.swift"
# - "../**/*Message.swift"
- "../**/Pairing*Message.swift"
# - "../**/TxStartRequestMessage.swift"
- "../**/remotepaylib/*.swift"
- "../**/TransformTypes.swift"
- "../**/*Transport.swift"
# - "../**/DisplayOrderMod*.swift"
- "../**/Initable.swift"
# - "../**/*Operation.swift"
- "../**/DefaultCloverConnectorListener.swift"
- "../**/ListWrapper.swift"
- "../**/CloverDeviceConfiguration.swift"
# - "../**/OrderActionResponse.swift"
- "../**/VoidCreditRe*.swift"


- "../**/Account.swift"
- "../**/AcknowledgementMessage.swift"
#- "../**/ActivityMessageFromActivity.swift"
#- "../**/ActivityMessageToActivity.swift"
- "../**/ActivityRequest.swift"
- "../**/ActivityResponseMessage.swift"
- "../**/AddDiscountAction.swift"
- "../**/AddLineItemAction.swift"
- "../**/Apps.swift"
#- "../**/AuthRequest.swift"
#- "../**/AuthResponse.swift"
- "../**/Base.swift"
#- "../**/BaseActivityMessage.swift"
#- "../**/BaseResponse.swift"
- "../**/BreakMessage.swift"
#- "../**/CapturePreAuthRequest.swift"
- "../**/CapturePreAuthRequestMessage.swift"
#- "../**/CapturePreAuthResponse.swift"
- "../**/CapturePreAuthResponseMessage.swift"
#- "../**/CardData.swift"
- "../**/CardDataRequestMessage.swift"
- "../**/CardDataResponseMessage.swift"
- "../**/Cash.swift"
- "../**/CashbackSelectedMessage.swift"
#- "../**/Challenge.swift"
# - "../**/CloseoutRequest.swift"
- "../**/CloseoutRequestMessage.swift"
#- "../**/CloseoutResponse.swift"
- "../**/CloseoutResponseMessage.swift"
# - "../**/CloverConnector.swift"
- "../**/CloverConnectorBroadcaster.swift"
# - "../**/CloverDevice.swift"
- "../**/CloverDeviceConfiguration.swift"
- "../**/CloverDeviceErrorEvent.swift"
- "../**/CloverDeviceEvent.swift"
- "../**/CloverDeviceFactory.swift"
- "../**/CloverDeviceObserver.swift"
- "../**/CloverTransport.swift"
- "../**/CloverTransportObserver.swift"
# - "../**/CLVModels.swift"
- "../**/ConfirmPaymentMessage.swift"
# - "../**/ConfirmPaymentRequest.swift"
# - "../**/CreditPrintMessage.swift"
# - "../**/CustomActivityRequest.swift"
# - "../**/CustomActivityResponse.swift"
# - "../**/Customers.swift"
# - "../**/DeclineCreditPrintMessage.swift"
# - "../**/DeclinePaymentPrintMessage.swift"
# - "../**/DefaultCloverConnectorListener.swift"
- "../**/DefaultCloverDevice.swift"
- "../**/Developer.swift"
- "../**/Device.swift"
# - "../**/DeviceStatusRequest.swift"
- "../**/DiscoveryRequestMessage.swift"
- "../**/DiscoveryResponseMessage.swift"
# - "../**/DisplayDiscount.swift"
# - "../**/DisplayLineItem.swift"
- "../**/DisplayModification.swift"
# - "../**/DisplayOrder.swift"
- "../**/DisplayOrderModifiedOperation.swift"
# - "../**/DisplayPayment.swift"
- "../**/Employees.swift"
# - "../**/ErrorCode.swift"
# - "../**/ExternalDeviceState.swift"
# - "../**/ExternalDeviceStateData.swift"
- "../**/FinishCancelMessage.swift"
- "../**/FinishOkMessage.swift"
- "../**/Hours.swift"
# - "../**/ICloverConnector.swift"
# - "../**/ICloverConnectorListener.swift"
- "../**/ImagePrintMessage.swift"
- "../**/Img.swift"
# - "../**/InputOption.swift"
- "../**/Inventory.swift"
# - "../**/KeyPress.swift"
- "../**/KeyPressMessage.swift"
- "../**/ListWrapper.swift"
# - "../**/ManualRefundRequest.swift"
# - "../**/ManualRefundResponse.swift"
- "../**/Merchant.swift"
# - "../**/MerchantInfo.swift"
- "../**/Message.swift"
# - "../**/MessageFromActivity.swift"
# - "../**/MessageToActivity.swift"
- "../**/Method.swift"
# - "../**/NetworkDeviceConfiguration"
- "../**/OpenCashDrawerMessage.swift"
# - "../**/Order.swift"
- "../**/OrderActionAddDiscountMessage.swift"
- "../**/OrderActionAddLineItemMessage.swift"
- "../**/OrderActionRemoveDiscountMessage.swift"
- "../**/OrderActionRemoveLineItemMessage.swift"
- "../**/OrderActionResponse.swift"
- "../**/OrderActionResponseMessage.swift"
- "../**/OrderUpdateMessage.swift"
- "../**/PairingCode.swift"
- "../**/PairingCodeMessage.swift"
# - "../**/PairingDeviceConfiguration.swift"
- "../**/PairingRequest.swift"
- "../**/PairingRequestMessage.swift"
- "../**/PairingResponse.swift"
# - "../**/PairingResponseMessage.swift"
- "../**/PartialAuthMessage.swift"
# - "../**/PayIntent.swift"
- "../**/PaymentConfirmedMessage.swift"
# - "../**/PaymentPrintMerchantCopyMessage.swift"
# - "../**/PaymentPrintMessage.swift"
# - "../**/PaymentResponse.swift"
# - "../**/Payments.swift"
- "../**/PaymentVoidedMessage.swift"
- "../**/PendingPaymentEntry.swift"
- "../**/Point.swift"
- "../**/Points.swift"
# - "../**/PreAuthRequest.swift"
# - "../**/PreAuthResponse.swift"
- "../**/Printer.swift"
# - "../**/PrintManualRefundDeclineReceiptMessage.swift"
# - "../**/PrintManualRefundReceiptMessage.swift"
# - "../**/PrintPaymentDeclineReceiptMessage.swift"
# - "../**/PrintPaymentMerchantCopyReceiptMessage.swift"
# - "../**/PrintPaymentReceiptMessage.swift"
# - "../**/PrintRefundPaymentReceiptMessage.swift"
# - "../**/ReadCardDataRequest.swift"
# - "../**/ReadCardDataResponse.swift"
- "../**/RefundPaymentPrintMessage.swift"
- "../**/RefundPaymentRequest.swift"
- "../**/RefundPaymentResponse.swift"
- "../**/RefundRequestMessage.swift"
- "../**/RefundResponseMessage.swift"
- "../**/RemoteMessage.swift"
- "../**/RemoteMessageType.swift"
- "../**/RemoveDiscountAction.swift"
- "../**/RemoveLineItemAction.swift"
# - "../**/ResetDeviceResponse.swift"
- "../**/ResetDeviceResponseMessage.swift"
# - "../**/ResultCode.swift"
# - "../**/ResultStatus.swift"
# - "../**/ResultStatusEnum.swift"
# - "../**/RetrieveDeviceStatusRequest.swift"
- "../**/RetrieveDeviceStatusRequestMessage.swift"
# - "../**/RetrieveDeviceStatusResponse.swift"
- "../**/RetrieveDeviceStatusResponseMessage.swift"
# - "../**/RetrievePaymentRequest.swift"
- "../**/RetrievePaymentRequestMessage.swift"
# - "../**/RetrievePaymentResponse.swift"
- "../**/RetrievePaymentResponseMessage.swift"
- "../**/RetrievePendingPaymentsRequestMessage.swift"
# - "../**/RetrievePendingPaymentsResponse.swift"
- "../**/RetrievePendingPaymentsResponseMessage.swift"
# - "../**/SaleRequest.swift"
# - "../**/SaleResponse.swift"
- "../**/ShowPaymentReceiptOptionsMessage.swift"
# - "../**/ShowPaymentReceiptOptionsRequest.swift"
- "../**/ShowThankYouScreenMessage.swift"
- "../**/ShowWelcomeScreenMessage.swift"
# - "../**/Signature.swift"
- "../**/SignatureVerifiedMessage.swift"
- "../**/TerminalMessage.swift"
- "../**/TextPrintMessage.swift"
# - "../**/TipAddedMessage.swift"
# - "../**/TipAdjustAuthRequest.swift"
# - "../**/TipAdjustAuthResponse.swift"
- "../**/TipAdjustMessage.swift"
- "../**/TipAdjustResponseMessage.swift"
# - "../**/TransactionRequest.swift"
# - "../**/TransactionType.swift"
- "../**/TransformTypes.swift"
- "../**/TxStartRequestMessage.swift"
- "../**/TxStartResponseMessage.swift"
- "../**/TxStartResponseResult.swift"
- "../**/TxState.swift"
- "../**/TxStateMessage.swift"
- "../**/UiStateMessage.swift"
- "../**/VaultCardMessage.swift"
# - "../**/VaultCardRequest.swift"
# - "../**/VaultCardResponse.swift"
- "../**/VaultCardResponseMessage.swift"
# - "../**/VerifySignatureRequest.swift"
- "../**/VoidCreditRequest.swift"
- "../**/VoidCreditResponse.swift"
- "../**/VoidPaymentMessage.swift"
# - "../**/VoidPaymentRequest.swift"
# - "../**/VoidPaymentResponse.swift"
# - "../**/VoidReason.swift"
- "../**/WebSocketCloverTransport.swift"
# - "../**/WebSocketDeviceConfiguration.swift"
