/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper

public class DisplayDiscount:Mappable {

  /*
  * Unique identifier
   */
  public var id:String? = nil
  /*
  * The lineItem with which the discount is associated
   */
  public var lineItemId:String? = nil
  /*
  * Name of the discount
   */
  public var name:String? = nil
  /*
  * Formatted discount amount
   */
  public var amount:String? = nil
  /*
  * Discount amount in percent
   */
  public var percentage:String? = nil

  public required init() {

  }

  required public init?(map: Map) {
  }

  public func mapping(map:Map) {
  id <- map["id"]

  lineItemId <- map["lineItemId"]

  name <- map["name"]

  amount <- map["amount"]

  percentage <- map["percentage"]

  }
}

