/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper




public class DisplayPayment:Mappable {

  /*
  * Unique identifier
   */
  var id:String? = nil 
  /*
  * Formatted display string for the tender e.g. credit card, cash, etc.
   */
  var label:String? = nil 
  /*
  * Formatted total amount paid
   */
  var amount:String? = nil 
  /*
  * Formatted amount paid in tips
   */
  var tipAmount:String? = nil 
  /*
  * Formatted amount paid in tax
   */
  var taxAmount:Int? = nil 

  public required init() {

  }

  required public init?(map:Map) {
  }

  public func mapping(map:Map) {
  id <- map["id"]

  label <- map["label"]

  amount <- map["amount"]

  tipAmount <- map["tipAmount"]

  taxAmount <- map["taxAmount"]

  }
}

