/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper

public class DisplayOrder:NSObject, Mappable {

  /*
  * Unique identifier
   */
  public var id:String? = nil
  /*
  * Currency of this order
   */
  public var currency:String? = nil
  /*
  * The employee associated with this order
   */
  public var employee:String? = nil
  /*
  * Formatted subtotal of the order
   */
  public var subtotal:String? = nil
  /*
  * Formatted tax of the order
   */
  public var tax:String? = nil
  /*
  * Formatted total of the order
   */
  public var total:String? = nil
  public var title:String? = nil
  public var note:String? = nil
  /*
  * Optional service charge name (gratuity) applied to this order
   */
  public var serviceChargeName:String? = nil
  /*
  * Optional service charge amount (gratuity) applied to this order
   */
  public var serviceChargeAmount:String? = nil
    public var discounts:Array<DisplayDiscount> = [DisplayDiscount]()//ListWrapper<DisplayDiscount>? = ListWrapper()
    public var lineItems:Array<DisplayLineItem> = [DisplayLineItem]()//ListWrapper<DisplayLineItem>? = ListWrapper()
  /*
  * Formatted amount remaining
   */
  public var amountRemaining:String? = nil
  /*
  * Payments that were made for this order
   */
  public var payments:Array<DisplayPayment>?//ListWrapper<DisplayPayment>? = nil

  public override required init() {
    super.init()
  }

  required public init?(map:Map) {
    super.init()
  }

  public func mapping(map:Map) {
    
      id <- map["id"]
      currency <- map["currency"]
      employee <- map["employee"]
      subtotal <- map["subtotal"]
      tax <- map["tax"]
      total <- map["total"]
      title <- map["title"]
      note <- map["note"]
      serviceChargeName <- map["serviceChargeName"]
      serviceChargeAmount <- map["serviceChargeAmount"]
      discounts <- map["discounts.elements"]
      lineItems <- map["lineItems.elements"]
      amountRemaining <- map["amountRemaining"]
      payments <- map["payments"]

  }
}

