
/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper

extension CLVModels {
  public class Printer {
    
    
    @objc(_TtCCC15CloverConnector9CLVModels7Printer7Printer)public class Printer: NSObject, NSCoding, Mappable {
      /// Unique identifier
      public var id: String?
      /// MAC address of a network printer
      public var mac: String?
      public var model: String?
      public var name: String?
      /// IP address of a network printer
      public var ipAddress: String?
      /// NETWORK is a printer that's directly connected to the network.  MY_LOCAL represents the printer that's connected to the device that's making the request.
      public var type_: CLVModels.Printer.PrinterType? = nil
      
      public func encode(with aCoder: NSCoder) {
        aCoder.encode(id, forKey: "id")
        aCoder.encode(mac, forKey: "mac")
        aCoder.encode(model, forKey: "model")
        aCoder.encode(name, forKey: "name")
        aCoder.encode(ipAddress, forKey: "ipAddress")
        aCoder.encode(type_?.rawValue, forKey: "type_")
      }
      
      required public init(coder aDecoder: NSCoder) {
        id = aDecoder.decodeObject(forKey: "id") as? String
        mac = aDecoder.decodeObject(forKey: "mac") as? String
        model = aDecoder.decodeObject(forKey: "model") as? String
        name = aDecoder.decodeObject(forKey: "name") as? String
        ipAddress = aDecoder.decodeObject(forKey: "ipAddress") as? String
        if let typeString = aDecoder.decodeObject(forKey: "type_") as? String {
            type_ = CLVModels.Printer.PrinterType(rawValue: typeString)
        }
      }
      
      override public init() {}
      
      // Mappable
      
      required public init?(map:Map) {}
      
      public func mapping(map:Map) {
        id <- map["id"]
        mac <- map["mac"]
        model <- map["model"]
        name <- map["name"]
        ipAddress <- map["ipAddress"]
        type_ <- map["type"]
      }
    }
    
    
    
    public enum PrinterType: String {
      case NETWORK
      case MY_LOCAL
    }
    
  }
}
