/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper



@objc
public class CloseoutRequest : NSObject {

  /*
  * Identifier for the request
   */
  var requestId:String? = nil 
  /*
  * Allow closeout if there are open tabs
   */
  var allowOpenTabs:Bool = false
  var batchId:String?
  var id:String? = nil 

    public init(allowOpenTabs:Bool, batchId:String?) {
        self.allowOpenTabs = allowOpenTabs
        self.batchId = batchId
    }

}

