/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper

public class CloseoutResponse:BaseResponse {

  /*
  * The batch that was closed out.
   */
  public var batch:CLVModels.Payments.Batch?


    public init(batch:CLVModels.Payments.Batch?, success:Bool, result:ResultCode) {
        super.init(success: success, result: result)
        self.batch = batch
    }
    
    required public init?(_ map: Map) {
        super.init(map)
    }
    
    public override func mapping(map: Map) {
        super.mapping(map)
        batch <- map["batch"]
    }
}

