/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper




public class Img:Mappable {

  /*
  * The url to the image if available
   */
  var src:String? = nil 
  /*
  * The width of the image if available
   */
  var width:Int? = nil 
  /*
  * The height of the image if available
   */
  var height:Int? = nil 

  public required init() {

  }

  required public init?(_ map: Map) {
  }

  public func mapping(map:Map) {
  src <- map["src"]

  width <- map["width"]

  height <- map["height"]

  }

/*
  public required init(jsonObj:NSDictionary){
    super.init()

  src = jsonObj.valueForKey("src") as! String?

  width = jsonObj.valueForKey("width") as! Int?

  height = jsonObj.valueForKey("height") as! Int?
  }
*/

}

