/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper


public class ManualRefundResponse:BaseResponse {

  public private(set) var credit:CLVModels.Payments.Credit?
  public private(set) var transactionNumber:String?

    

    init(success:Bool, result:ResultCode, credit:CLVModels.Payments.Credit?=nil, transactionNumber:String?=nil, reason:String?=nil) {
        super.init(success:success, result:result, reason:reason, message:nil)
        self.credit = credit
        self.transactionNumber = transactionNumber
    }
    
    required public init?(_ map: Map) {
        super.init(map)
    }
    
    public override func mapping(map: Map) {
        super.mapping(map)
        credit <- (map["credit"], Message.creditTransform)
        transactionNumber <- map["transactionNumber"]
    }
    
}

