/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper




public class Points:Mappable {

//  var points:ListWrapper<Point>? = nil
  var points:[Point] = [Point]()

  public required init() {

  }

  required public init?(_ map: Map) {
  }

  public func mapping(map:Map) {
    points <- map["points"]

  }

/*
  public required init(jsonObj:NSDictionary){
    super.init()

  points = ListWrapper<Point>(jsonObj: jsonObj.valueForKey("points") as! NSDictionary)

  }
*/

}

