/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import Foundation
import ObjectMapper


public class PreAuthResponse:PaymentResponse {
    public init(success:Bool, result:ResultCode) {
        super.init(success:success, result:result)
    }
    
    required public init?(_ map: Map) {
        super.init(map)
    }

}

