/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */


public enum ResultStatus:String {
  case SUCCESS = "SUCCESS"
  case FAIL = "FAIL"
  case CANCELED = "CANCELED"
  case CANCEL = "CANCEL"
  case ERROR = "ERROR"
}


