/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper


public class TipAdjustAuthResponse : BaseResponse {

  /*
  * Total amount paid
   */
  public private(set) var tipAmount:Int?
  /*
  * The payment from the sale
   */
  public private(set) var paymentId:String?
    public private(set) var orderId:String?

    public required init(success:Bool, result:ResultCode, paymentId:String?, tipAmount:Int?) {
        super.init(success: success, result:result)
        self.paymentId = paymentId
        self.tipAmount = tipAmount
  }
    
    required public init?(_ map: Map) {
        super.init(map)
    }
    
    public override func mapping(map: Map) {
        super.mapping(map)
        paymentId <- map["paymentId"]
        tipAmount <- map["tipAmount"]
        orderId <- map["orderId"]
    }

}

