/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper


@objc
public class TipAdjustAuthRequest : NSObject, Mappable {

    /*
     * Amount paid in tips
     */
    public var tipAmount:Int
    /*
     * Unique identifier
     */
    public var orderId:String
    /*
     * Unique identifier
     */
    public var paymentId:String
    
    public required init(orderId: String, paymentId: String, tipAmount:Int) {
        self.tipAmount = tipAmount
        self.orderId = orderId
        self.paymentId = paymentId
    }
    
    public required init?(_ map: Map) {
        orderId = ""
        paymentId = ""
        tipAmount = 0
        super.init()
    }
    
    public func mapping(map: Map) {
        tipAmount <- map["tipAmount"]
        orderId <- map["orderId"]
        paymentId <- map["orderId"]
    }

}

