/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper


public class VaultCardResponse:BaseResponse {

  public var card:CLVModels.Payments.VaultedCard? = nil

    public override init(success:Bool, result:ResultCode) {
        super.init(success:success, result: result);
    }
    public init(card:CLVModels.Payments.VaultedCard?, code:ResultStatus, reason:String?) {
        super.init(success:code == .SUCCESS, result:code == .SUCCESS ? ResultCode.SUCCESS : ResultCode.FAIL)
        self.card = card
    }
    
    required public init?(_ map: Map) {
        super.init(map)
    }
    
    public override func mapping(map: Map) {
        super.mapping(map)
        card <- map["card"]
    }
}

