/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */

import ObjectMapper

@objc
public class VoidPaymentRequest:NSObject, Mappable {

  /*
  * Unique identifier
   */
  var orderId:String? = nil 
  /*
  * Unique identifier
   */
  var paymentId:String?
    
  var voidReason:VoidReason

  public required init(orderId:String, paymentId:String, voidReason:VoidReason) {
        self.orderId = orderId
        self.paymentId = paymentId
        self.voidReason = voidReason
        super.init()
  }
    
    public required init?(_ map: Map) {
        voidReason = .USER_CANCEL
        super.init()
    }
    
    public func mapping(map: Map) {
        
        orderId <- map["orderId"]
        paymentId <- map["paymentId"]
        voidReason <- map["voidReason"]
    }

}

